---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-cluster
  namespace: flux-cluster
spec:
  interval: 24h0s
  path: ./base/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  validation: client
