---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kind
  namespace: flux-cluster
spec:
  interval: 24h0s
  path: ./kind/
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-gitops-flux-cluster
  validation: client
