---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-cluster
resources:
  - ../base/flux-cluster/
  - infrastructure.yaml
  - applications.yaml
patchesStrategicMerge:
  - flux-cluster.patch.yaml
