---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: podinfo
  namespace: base
spec:
  interval: 24h
  ref:
    branch: master
  secretRef:
    name: github-credentials
  url: https://github.com/stefanprodan/podinfo.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo
  namespace: base
spec:
  interval: 24h0s
  path: ./deploy/overlays/base/
  prune: true
  sourceRef:
    kind: GitRepository
    name: podinfo
  validation: client
