---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: applications
  namespace: flux-cluster
spec:
  interval: 24h
  sourceRef:
    kind: GitRepository
    name: clusters
  path: ./base/applications/
  prune: true
  validation: client
  patches:
    - patch: |-
        - op: replace
          path: /spec/path
          value: ./deploy/prod/
      target:
        group: kustomize.toolkit.fluxcd.io
        version: v1beta1
        kind: Kustomization
