---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: prod
  namespace: flux-cluster
spec:
  interval: 24h
  path: ./prod/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  validation: client
