---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-cluster
spec:
  interval: 24h
  sourceRef:
    kind: GitRepository
    name: k8s-gitops-flux-cluster
  path: ./base/infrastructure/
  prune: true
  validation: client
  patches:
    - patch: |-
        - op: replace
          path: /spec/path
          value: ./lab/
      target:
        group: kustomize.toolkit.fluxcd.io
        version: v1beta1
        kind: Kustomization
