---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: lab
  namespace: flux-cluster
spec:
  interval: 24h
  path: ./lab/
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-gitops-flux-cluster
  validation: client
